translations={
    "en":{
        "title":"KrishakAI Pest Detection",
        "home":"Home",
        "image_detection":"Image Detection",
        "camera_detection":"Camera Detection",
        "dashboard":"Dashboard",
        "heatmap":"Heatmap",
        "ai_crop_doctor":"AI Crop Doctor",
        "help_desk":"Help Desk",
        "logout":"Logout",
        "upload":"Upload Crop Image",
        "camera_instruction":"Open the app in your browser, allow camera access when prompted, and take a photo of the affected plant.",
        "camera_tip":"Rotate your phone into landscape mode for better framing. Hold steady and ensure good lighting.",
        "camera_capture":"Take a photo of the crop",
        "location_help":"Enter your coordinates or use a location service to get latitude and longitude.",
        "your_location":"Your location",
        "heatmap_intro":"Use the map to view pest hotspots and healthy fields.",
        "help_home":"Welcome page shows the main feature overview and navigation.",
        "help_image":"Upload images to detect pests and save results to your dashboard.",
        "help_camera":"Use the camera to capture plant images for real-time pest detection.",
        "help_dashboard":"View pest detection history and risk trend charts.",
        "help_heatmap":"See pest hotspots and healthy areas on an interactive map.",
        "help_doctor":"Describe symptoms and get AI-driven diagnosis and treatment advice.",
        "home_subtitle":"AI powered pest monitoring system for sustainable agriculture",
        "home_description":"KrishakAI helps farmers detect crop pests early using AI. Uploads crop images to detect infestations.",
        "feature_pest_detection":"Pest Detection",
        "feature_camera":"Real-time Camera Monitoring",
        "feature_dashboard":"Farmer Dashboard",
        "feature_doctor":"AI Crop Doctor",
        "feature_heatmap":"Pest Heatmap",
        "features_title":"Features",
        "camera_idle":"Use the camera control above to take a photo and run pest detection.",
        "camera_select_crop":"Select Crop for Treatment Recommendations",
        "camera_preview_tip":"If you want a raw preview without detections, enable the preview mode.",
        "heatmap_lat":"Your Latitude",
        "heatmap_lon":"Your Longitude",
        "heatmap_your_location":"Your location",
        "heatmap_intro":"Use the map to view pest hotspots and healthy fields.",
        "voice_assistant":"Voice Assistant",
        "voice_help":"Ask questions in English or Hindi by voice, and get answers through voice response.",
        "start_recording":"Start Recording",
        "manual_input":"Manual Input",
        "your_question":"Your Question",
        "response":"Response",
        "playing_response":"Playing response...",
        "ask_another":"Ask Another Question",
        "listening":"Listening... Please speak now",
        "recognized":"Recognized"
    },
    "hi":{
        "title":"कृषकAI कीट पहचान प्रणाली",
        "home":"होम",
        "image_detection":"इमेज पहचान",
        "camera_detection":"कैमरा पहचान",
        "dashboard":"डैशबोर्ड",
        "heatmap":"हीटमैप",
        "ai_crop_doctor":"एआई फ़सल डॉक्टर",
        "help_desk":"हेल्प डेस्क",
        "logout":"लॉग आउट",
        "upload":"फसल की तस्वीर अपलोड करें",
        "camera_instruction":"अपने ब्राउज़र में ऐप खोलें, जब पूछा जाए तो कैमरा एक्सेस की अनुमति दें, और प्रभावित पौधे की फोटो लें।",
        "camera_tip":"बेहतर फ़्रेमिंग के लिए अपने फोन को लैंडस्केप मोड में घुमाएँ। स्थिर रखें और अच्छी रोशनी सुनिश्चित करें।",
        "camera_capture":"फसल की फोटो लें",
        "location_help":"अपनी निर्देशांक दर्ज करें या अपनी स्थिति प्राप्त करने के लिए कोई स्थान सेवा उपयोग करें।",
        "your_location":"आपका स्थान",
        "heatmap_intro":"मानचित्र का उपयोग कीट हॉटस्पॉट और स्वस्थ क्षेत्रों को देखने के लिए करें।",
        "help_home":"मुख्य फ़ीचर अवलोकन और नेविगेशन दिखाता है।",
        "help_image":"कीटों का पता लगाने के लिए छवियों को अपलोड करें और परिणाम अपने डैशबोर्ड में सहेजें।",
        "help_camera":"वास्तविक समय कीट पहचान के लिए पौधे की छवि लेने के लिए कैमरा का उपयोग करें।",
        "help_dashboard":"कीट पता लगाने का इतिहास और जोखिम रुझान चार्ट देखें।",
        "help_heatmap":"इंटरैक्टिव मानचित्र पर कीट हॉटस्पॉट और स्वस्थ क्षेत्रों को देखें।",
        "help_doctor":"लक्षणों का वर्णन करें और एआई-आधारित निदान और उपचार सलाह प्राप्त करें।",
        "home_subtitle":"सतत कृषि के लिए एआई संचालित कीट निगरानी प्रणाली",
        "home_description":"कृषकAI किसानों को कीटों का जल्दी पता लगाने में मदद करता है। छवि अपलोड करें और कीट पहचान करें।",
        "feature_pest_detection":"कीट पहचान",
        "feature_camera":"वास्तविक समय कैमरा मॉनिटरिंग",
        "feature_dashboard":"किसान डैशबोर्ड",
        "feature_doctor":"एआई फ़सल डॉक्टर",
        "feature_heatmap":"कीट हीटमैप",
        "features_title":"फ़ीचर",
        "camera_idle":"फोटो लेने और कीट पहचान चलाने के लिए ऊपर दिए गए कैमरा नियंत्रण का उपयोग करें।",
        "camera_select_crop":"उपचार सिफारिशों के लिए फसल चुनें",
        "camera_preview_tip":"यदि आप बिना पहचान के केवल कच्चा पूर्वावलोकन देखना चाहते हैं, तो पूर्वावलोकन मोड सक्षम करें।",
        "camera_capture_again":"फिर से फ़ोटो लें",
        "camera_no_pests":"कोई कीट नहीं मिला। अलग कोण या बेहतर रोशनी आज़माएँ।",
        "heatmap_lat":"आपकी अक्षांश",
        "heatmap_lon":"आपकी देशांतर",
        "heatmap_your_location":"आपका स्थान",
        "heatmap_intro":"कीट हॉटस्पॉट और स्वस्थ क्षेत्रों को देखने के लिए मानचित्र का उपयोग करें।",
        "voice_assistant":"वॉयस सहायक",
        "voice_help":"अंग्रेजी या हिंदी में वॉयस द्वारा प्रश्न पूछें, और वॉयस प्रतिक्रिया के माध्यम से उत्तर प्राप्त करें।",
        "start_recording":"रिकॉर्डिंग शुरू करें",
        "manual_input":"मैनुअल इनपुट",
        "your_question":"आपका प्रश्न",
        "response":"जवाब",
        "playing_response":"जवाब चला रहे हैं...",
        "ask_another":"एक और सवाल पूछें",
        "listening":"सुनिच्छा रहा हूँ... अब बोलिए",
        "recognized":"पहचाना गया"
    }
}